### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by siavashMehran** [sadafamininia99/Exchange-Rate-Calculator#1]
hey your projects are good but none of em have documentations or any form of easy representation

add a `README.md` to your projects
at least put the links to `GITHUB STATIC PAGE` of that project in it, or some screenshot

try this for all of your repos

**Comment by sadafamininia99** [comment]
**hi**
thank you for this recommendation _i try it_

**Comment by siavashMehran** [comment]
🖐😬
